apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-demo-deployment
  labels:
    app: go-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
      - name: go-demo
        image: gcr.io/endocode-playground/go-demo:latest
        ports:
        - containerPort: 5000
